### ISSUE TITLE
SSH keys generated on hosts should be password-protected

### ISSUE THREAD

**Issue by alecigne** [alecigne/ansible-desktop#3]
```
- name: Generate a new SSH key
  openssh_keypair:
    path: "~/.ssh/{{ ssh_key_name }}"
    type: ed25519
  register: ssh_key
```
This generates an unprotected SSH key on hosts.
